# Generated by Django 5.2.4 on 2025-07-27 04:47

import django.utils.timezone
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('resumen', django_summernote.fields.SummernoteTextField(blank=True, max_length=1000)),
                ('imagen', models.ImageField(blank=True, default='posts/post_default.png', null=True, upload_to='posts')),
                ('contenido', django_summernote.fields.SummernoteTextField(verbose_name='Escriba aqui el contenido')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('publicado', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-publicado',),
            },
        ),
    ]
