# Generated by Django 5.2.4 on 2025-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
